services:
  db:
    container_name: sisdrenagem-db
    image: sisdrenagem/db
    restart: no 
    shm_size: 256mb
    env_file: .env
    ports:
      - $PG_LOCAL_PORT:$PG_DOCKER_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_INITDB_ARGS=$POSTGRES_INITDB_ARGS
  api:
    container_name: sisdrenagem-api
    image: sisdrenagem/api
    restart: no 
    env_file: .env
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    depends_on: [db]
  ui:
    container_name: sisdrenagem-ui
    image: sisdrenagem/ui
    restart: no 
    env_file: .env
    ports:
      - $VITE_LOCAL_PORT:$VITE_DOCKER_PORT
    depends_on: [db,api]
